global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'buku-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['buku-service:8001']

  - job_name: 'anggota-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['anggota-service:8002']

  - job_name: 'peminjaman-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['peminjaman-service:8003']

  - job_name: 'pengembalian-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pengembalian-service:8004']

  - job_name: 'notifikasi-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notifikasi-service:8085']
