## YAML Template.
---
server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
                server:
                    webmvc:
                        routes:
                            - id: PRODUK-SERVICE
                              uri: lb://PRODUK
                              predicates: 
                                - Path=api/produk/**
                            - id: PELANGGAN-SERVICE
                              uri: lb://PELANGGAN
                              predicates: 
                                - Path=api/pelanggan/**
                            - id: ORDER-SERVICE
                              uri: lb://ORDER
                              predicates: 
                                - Path=api/order/**
                            - id: ANGGOTA-SERVICE
                              uri: lb://ANGGOTA
                              predicates: 
                                - Path=api/anggota/**
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost